berita/urls.py
from django.urls import path
from . import views
from .views import showBeritaViews, search_news, beritaSearchView
from django.views.decorators.csrf import csrf_exempt

app_name = 'berita'

urlpatterns = [
    path('', showBeritaViews.as_view(), name='beritahome'),
    path('beritasearch/', beritaSearchView, name='beritasearch'),
    path('searchresults/', csrf_exempt(search_news), name='search-results'),
]

bintang/urls.py
from django.urls import path
from django.conf.urls import url 

from . import views

app_name = 'bintang'

urlpatterns = [
    path('submisi/', views.submisi, name='submisi'),
    path('detail/<int:detail_id>', views.detail, name='detail'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
    
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('data/', views.searchhospital, name="searchhospital"), #BintangNumpang
    path('feedback/', views.feedback, name="feedback"),
    path('masukkan/', views.masukkan, name='masukkan'),
]

projectsaveus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('stats/', include('stats.urls')),
    path('bintang/', include('bintang.urls')),
    path('detil/', include('detil.urls')),
    path('berita/', include('berita.urls')),
    path('tips/', include('tips.urls')),
    path('authe/', include('authentication.urls')),
    path('betterstats/', include('betterstats.urls'))
]

home/models.py
from django.db import models

class ShowSubmisi(models.Model):
    pass
            
class FeedBack(models.Model):
    nama_feedback = models.CharField(max_length = 50)
    feedback_pencerita = models.TextField(max_length = 700)

    def __stf__(self):
        return "{}. {}".format(self.id, self.nama_pencerita)

# temporary model
# class Cerita(models.Model):
#     nama_pencerita = models.CharField(max_length=50)
#     email_pencerita = models.EmailField(max_length=50)
#     judul_pencerita = models.CharField(max_length=50, null=True)
#     cerita_pencerita = models.TextField(blank=False, null=False)
#     published = models.DateTimeField(auto_now_add=True)
#     submisi = models.ForeignKey(ShowSubmisi, on_delete=models.CASCADE)

#     def __str__(self):
#         return f"{self.id}. {self.nama_pencerita}"

#     def save(self, *args, **kwargs):
#         count = 1
#         if self.submisi.cerita_set.filter(email_pencerita=self.email_pencerita).exists():
#             self.id = self.submisi.cerita_set.count()
#         else :
#             self.id = self.submisi.cerita_set.count()+1
#         for i in self.submisi.cerita_set.all():
#             self.submisi.cerita_set.filter(id=i.id).update(id=count)
#             count += 1
#         super(Cerita, self).save(*args, **kwargs)

home/views.py
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.template.loader import render_to_string
from .models import ShowSubmisi, FeedBack
from django.core.exceptions import ObjectDoesNotExist
from django.db.models.functions import Lower

#BintangNumpang
from django.http import JsonResponse
from django.http import HttpResponse
import requests
import json
# Create your views here.

def index(request):


    if ShowSubmisi.objects.all().count() == 0:
        submisi = ShowSubmisi.objects.create(id=1)
    else:
        count = ShowSubmisi.objects.count()
        for i in range(1,count):
            ShowSubmisi.objects.all()[i].delete()
        submisi = ShowSubmisi.objects.all()[0]
        ShowSubmisi.objects.filter(id=submisi.id).update(id=1)

    if request.is_ajax():
        data = ''
        # Search
        if 's1' in request.GET:
            keyword = request.GET['s1']
            data = submisi.cerita_set.filter(judul_pencerita__istartswith=keyword)
        # Sort
        elif 'sort' in request.GET:
            keyword = request.GET['sort']    
            # berdasarkan judul
            if keyword == '0':
                data = submisi.cerita_set.order_by(Lower('judul_pencerita'))
            # berdasarkan tanggal (recently)
            if keyword == '1':
                data = submisi.cerita_set.order_by('-published')
        html = render_to_string(
            template_name='home/ajax_card.html',
            context={'ceritas':data}
        )

        return JsonResponse(data={'cerita':html})

    cerita_user_logged_in = None
    if request.user.is_authenticated :
        try:
            cerita_user_logged_in = submisi.cerita_set.filter(email_pencerita=request.user.email)
        except ObjectDoesNotExist:
            cerita_user_logged_in = None
    # initialize
    cerita = submisi.cerita_set.order_by('-published')
    context = {
        'ceritas': cerita, 'cerita_user':cerita_user_logged_in
    }
    return render(request, 'home/index.html', context)


#BintangNumpang
def searchhospital(request):
    url = 'https://dekontaminasi.com/api/id/covid19/hospitals/'
    retrive = requests.get(url)
    data = json.loads(retrive.content)
    return JsonResponse(data, safe=False)
    
def feedback(request):
    if request.method == "POST":
        nama_feedback = request.POST['nama_feedback']
        feedback_pencerita = request.POST['feedback_pencerita']

        FeedBack.objects.create(
            nama_feedback = nama_feedback,
            feedback_pencerita = feedback_pencerita,
        )

        return redirect('home:index')

def masukkan(request):
    masukkan = FeedBack.objects.all()
    context = {
        'masukkan' : masukkan,
    }
    return render(request, 'home/masukkan.html', context)

home/templates/home/ajax_card.html
{% if ceritas %}
    {% for cerita in ceritas %}
    <div class="card bg-light mb-3 submisi-card swiper-submisi-slide" style="width: 350px;">
        <div class="card-header">Submisi #{{ forloop.counter }}</div>
        <div class="card-body">
            <h5 class="card-title">{{ cerita.judul_pencerita }}</h5>
            <h6 class="card-subtitle">oleh {{ cerita.nama_pencerita }}</h6>
        </div>
        <a class="btn btn-primary" href="{% url 'bintang:detail' cerita.id %}"
        style="color: aliceblue;">Baca Selengkapnya</a><br>
        <div class="card-footer">
            <p class="card-text">
                {{ cerita.published }}
            </p>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h3>Cerita tidak ditemukan.</h3>
{% endif %}

home/templates/home/index.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Homepage</title>
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

{% endblock meta %}

{% block content %}


<!-- Slider main container -->
<div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide">
            <img src="{% static 'img/Banner1_covid.svg' %}" alt="">
        </div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
        ...
    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>
    
    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    
    <!-- If we need scrollbar -->
    <div class="swiper-scrollbar"></div>
</div>

{% if user.is_authenticated %}
<div class="welcome d-flex justify-content-center">
    <h2>Welcome, {{ user.first_name }}</h2>
</div>
{% endif %}

<div class="middle">
    <div class="peta">
        <div class="peta-img">
            <img src="{% static 'img/peta1.png' %}" alt="">
        </div>
        <div class="peta-text">
            <h1>Persebaran</h1>
            <h1 style="color: rgb(238, 22, 22);">Covid-19</h1>
            <h1>Di</h1>
            <h1>Daerah</h1>
            <h1>Ibu Kota</h1>
            
            <a href="{% url 'berita:beritahome' %}" class="btn btn-info info-sel">INFO SELENGKAPNYA</a>
        </div>
    </div>
</div>

<div class="subm">
    <div class="submisi-title">
        <h2 style="color: rgb(238, 22, 22);">Cari Rumah Sakit</h2>
        <p>Pencarian berdasarkan provinsi di Indonesia</p>
    </div>
    <input type="text" name="search_1" id="keyword" class="form-control" placeholder="Contoh: DKI Jakarta" style="margin: 30px; ">
    <ol id="hasil">
        
    </ol>
</div>

<div class="subm">
    <div class="submisi-title">
        <h2>Cerita Untuk Kamu</h2>
    </div>
    
    <div class="forms d-flex" style="margin: 20px 0 0 20px;">
        <input type="text" name="search_1" id="id_search_1" class="form-control" placeholder="Judul cerita...">
        <select class="form-control" name="sortby" id="id_sortby">
            <option value="0">Judul</option>
            <option value="1" selected="selected">Recently</option>
        </select>
    </div>
    
    <div class="content">
        <div class="swiper-submisi">
            <div class="swiper-submisi-wrapper" id="first">
                {% if ceritas.count != 0 %}
                {% for cerita in ceritas %}
                <div class="card bg-light mb-3 submisi-card swiper-submisi-slide" style="width: 350px;">
                    <div class="card-header">Submisi #{{ forloop.counter }}</div>
                    <div class="card-body">
                        <h5 class="card-title">{{ cerita.judul_pencerita }}</h5>
                        <h6 class="card-subtitle">oleh {{ cerita.nama_pencerita }}</h6>
                    </div>
                    <a class="btn btn-primary" href="{% url 'bintang:detail' cerita.id %}"
                    style="color: aliceblue;">Baca Selengkapnya</a><br>
                    <div class="card-footer">
                        <p class="card-text">
                            {{ cerita.published }}
                        </p>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="swiper-submisi-pagination"></div>
            <div class="swiper-submisi-scrollbar"></div>
        </div>
    </div>
</div>

{% if user.is_authenticated %}
<div class="subm">
    <div class="submisi-title">
        <h2>Cerita Dari Kamu</h2>
    </div>

    <div class="content">
        <div class="swiper-submisi">
            <div class="swiper-submisi-wrapper" id="second">
                {% if cerita_user.count != 0 %}
                {% for cerita in cerita_user %}
                <div class="card bg-light mb-3 submisi-card swiper-submisi-slide" style="width: 350px;">
                    <div class="card-header">Submisi #{{ forloop.counter }}</div>
                        <div class="card-body">
                            <h5 class="card-title">{{ cerita.judul_pencerita }}</h5>
                            <h6 class="card-subtitle">oleh {{ cerita.nama_pencerita }}</h6>
                        </div>
                        <a class="btn btn-primary" href="{% url 'bintang:detail' cerita.id %}"
                        style="color: aliceblue;">Baca Selengkapnya</a><br>
                        <a class="btn btn-danger" href="{% url 'bintang:delete' cerita.id %}" title="">Hapus Cerita Ini</a>
                        <div class="card-footer">
                            <p class="card-text">
                                {{ cerita.published }}
                            </p>
                        </div>
                    </div>
                  
                    {% endfor %}
                    {% else %}
                    <div style="width: 100%;">
                        <h3 style="text-align: center;">Belum ada cerita</h3>
                    </div>
                    
                {% endif %}
            </div>
            {% if cerita_user.count != 0 %}
            <div class="swiper-submisi-pagination"></div>
            <div class="swiper-submisi-scrollbar"></div>
            {% endif %}
        </div>
    </div>
</div>
{% endif %}

<!-- bintangnumpang -->

<div class="to-submisi">
    <h1>Ayo ceritakan kisah atau tips-mu dalam menghadapi pandemi ini!</h1>
    <a href="{% url 'bintang:submisi' %}" class="btn btn-to-submisi">KLIK DISINI</a>
</div>

<div class="container-form">
    <form method="POST" id="new_user_form">
        {% csrf_token %}
        
        <div class="form-group">
            <input type="hidden" id="nama_feedback" name="nama_feedback" value="{{ user.first_name }}">
        </div>
        <div class="form-group">
            Feedback <br>
            <textarea type="text" id="feedback_pencerita" name="feedback_pencerita"></textarea>
        </div>
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</div>

{% endblock content %}

{% block jsfile %}
<script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script src="{% static 'js/home.js' %}" type="text/javascript"></script>
<script src="{% static 'js/ajax_call.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bintang.js' %}" type="text/javascript"></script>

{% endblock jsfile %}

home/templates/home/masukkan.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Homepage</title>
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="{% static 'js/bintang.js' %}" type="text/javascript"></script>
{% endblock meta %}

{% block content %}

<div>
    {% for isi in masukkan %}
    <p>{{isi.feedback_pencerita}}<p>
    {% endfor %}
</div>

{% endblock content %}

{% block jsfile %}
<script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script src="{% static 'js/home.js' %}"></script>
<script src="{% static 'js/ajax_call.js' %}"></script>

{% endblock jsfile %}