berita/urls.py
from django.urls import path
from . import views
from .views import showBeritaViews, search_news, beritaSearchView
from django.views.decorators.csrf import csrf_exempt

app_name = 'berita'

urlpatterns = [
    path('', showBeritaViews.as_view(), name='beritahome'),
    path('beritasearch/', beritaSearchView, name='beritasearch'),
    path('searchresults/', csrf_exempt(search_news), name='search-results'),
]

bintang/urls.py
from django.urls import path
from django.conf.urls import url 

from . import views

app_name = 'bintang'

urlpatterns = [
    path('submisi/', views.submisi, name='submisi'),
    path('detail/<int:detail_id>', views.detail, name='detail'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
    
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('data/', views.searchhospital, name="searchhospital"), #BintangNumpang
    path('feedback/', views.feedback, name="feedback"),
    path('masukkan/', views.masukkan, name='masukkan'),
]

projectsaveus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('stats/', include('stats.urls')),
    path('bintang/', include('bintang.urls')),
    path('detil/', include('detil.urls')),
    path('berita/', include('berita.urls')),
    path('tips/', include('tips.urls')),
    path('authe/', include('authentication.urls')),
    path('betterstats/', include('betterstats.urls'))
]

stats/urls.py
from django.urls import path
from . import views
from .views import showprovinsiView


app_name = 'stats'

urlpatterns = [
    path('', showprovinsiView.as_view(), name='stathome'),
]

tips/urls.py
from django.urls import path
from . import views

app_name = 'tips'

urlpatterns = [
    path('cuci-tangan/', views.cuci_tangan, name='cuci_tangan'),
    path('di-rumah/', views.di_rumah, name='di_rumah'),
    path('di-luar-rumah', views.di_luar_rumah, name='di_luar_rumah'),
    path('', views.add_jurnal, name='add_jurnal'),
    path('view-jurnal/', views.view_jurnal, name='view_jurnal'),
    
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  
  <!-- Font Awesome -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/e76dc76644.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">  
  {% block meta %}
  
  {% endblock meta %}
</head>
<body>
    <header>
        <nav>
            <img src="{% static 'img/us_logo.svg' %}" alt="" class="logo">
            <a href="{% url 'home:index' %}">Beranda</a>
            <a href="{% url 'berita:beritahome' %}">Berita</a>
            <a href="{% url 'stats:stathome' %}">Statistik</a>
            <a href="{% url 'tips:add_jurnal' %}">Tindakan</a>
            <a href="{% url 'bintang:submisi' %}">Submisi</a>
            {% if user.is_authenticated %}
            <a href="{% url 'authentication:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'authentication:login' %}">Login</a>
            {% endif %}
        </nav>
    </header>
    {% block content %}
    
    {% endblock content %}
    <footer>
        <h6>FOLLOW US ON</h6>
        <div class="social">
            <a href="#"><i class="fab fa-twitter"></i> <p>@projectsaveus</p></a>
            <a href="#"><i class="fab fa-instagram"></i> <p>@projectsaveus</p></a>
        </div>
        <div class="copyright"><p>Copyright © 2020 ProjectSaveUs</p></div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="crossorigin="anonymous"></script>  
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    {% block jsfile %}
    
    {% endblock jsfile %}
</body>
</html>